name: ${project.name}
version: ${project.version}
description: ${project.description}
author: regulad

main: xyz.regulad.demochat.DemoChatPlugin
api-version: 1.17
libraries:
  - org.jetbrains:annotations:23.0.0
  - com.zaxxer:HikariCP:5.0.0

permissions:
  demochat.*:
    description: Grants access to all permissions.
    children:
      - "demochat.commands.*"
  demochat.commands.*:
    description: Grants access to all commands.
    children:
      - "demochat.commands.createchannel"
      - "demochat.commands.removechannel"
      - "demochat.commands.changechannel"
  demochat.commands.createchannel:
    description: Adds a chat chanenl to the plugin.
    default: op
  demochat.commands.removechannel:
    description: Removes a chat channel from the plugin.
    default: op
  demochat.commands.changechannel:
    default: true
    description: Allows a player to change their channel.
  demochat.commands.togglefilter:
    default: true
    description: Allows a player to toggle the filter.

commands:
  togglefilter:
    aliases:
      - "filter"
    permission: "demochat.commands.togglefilter"
    description: "Toggles the filter."
    usage: "Usage: /<command>"
  createchannel:
    permission: "demochat.commands.createchannel"
    description: "Adds a channel to the server."
    usage: "Usage: /<command> <Name of channel> <Same world> <Distance>"
  removechannel:
    permission: "demochat.commands.removechannel"
    description: "Removes a channel from the server."
    usage: "Usage: /<command> <Name of channel>"
  changechannel:
    permission: "demochat.commands.changechannel"
    description: "Changes your channel."
    usage: "Usage: /<command> <Name of channel>"
    aliases:
      - "c"
